# Default values for ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  development: false
  serviceType: ClusterIP

# This is one generated just for SP stuff, which is superior to using the default nginx one. Even
# better, generate your own and put it here!
dhParam: LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KICBNSUlDQ0FLQ0FnRUFtOVRXRTA2bHdJZHN6MklWYW9LS09IQ0pCV09NSFdXWk9TVy9xYTM5NnliK1B3RnpHNFVTCiAgUUd0bkEwTTRMdzdIR1hNLyt2VUFVcmFoRi83Z2NhckF1cnE1MnhoMVJtNXdmeTVlMEJWZkhueENIM1BueDl4RQogIFhiNlE4ZURSMG96THd6blJKYWkySzV2WDZLQ0dId1VLR0dHUDN3RGZMbml1Wm5oTUFRM1pySk9GN1NBZ0kvOWYKICBkK1hhMVlTd3ljVTBINUw1QmgzWGFHZXkxc3EwaE95em5lL0lXeFhtMEhKZW4yMmduTlp2QkxTSFlYK0ZzTVBwCiAgaTdQWFBUS0s2KzV4UDkwN2tEV2c4dUYzdHNhanRMYmxMZnovRHlzZDFkYVJONzZ2Mlg0ZjJrQ01UQWFSdDl4cwogIDhUeDV6Q2FuNnBYMDVFZllWZGxHSDcyMEtvRlltS25pYXMvcTNlV3Rackx3YVMzemJ2Ny90enFXd0JZQi9vVFkKICBSRjZjZmYwNit1MVByL24vUEc0di9oRnU4TS9QS25MQTFYSUFQZGJTc3lSWndxYWtYT2FIU1lyb1YxbTZnaHB2CiAgQ3FoZGZtODdUdUQzaGFxbnEwUDNzUE1PaDhYd0JJdnFyNUo3ZVZ1Vm9XeU5Xa09acjBVekgrTXVnSThuQXIxZAogIHpjazEvVFFyL2djS1FLYTRNMncxZGtxSFEyaFhVeWduK3RUZmxKV2lWeW1YWWJ2MWVwL1d3ZGM1TUROOG1rbTgKICBHRUJ2T2FDRktnbnl6UWxoU3F5TG1zRkRNd0xRT09EcGlTeUFOTklHRGtOcGxoeVBNRktPcEt2WEVkRXZnRjhDCiAgVWFXMXdLdlZxcmc5WTh0VmJ5SGRBaDliMm95Nnd1NFREVHYrclhCUUtrc3ovZjkrL2JzSnIvTUNBUUk9CiAgLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0t
